### ISSUE TITLE
ubuntu compatibility: missing dependency

### ISSUE THREAD

**Issue by rynnon** [maestrogerardo/i3-gaps-deb#1]
The dependency libxcb-xrm-dev does not exist on Ubuntu 16.04, and thus the build fails. It's possible that it's functionality is provided by another package, as I have installed i3-gaps manually in a VM before, but dpkg wants libxcb-xrm-dev.

Relevant terminal output:
>[igd] Build Debian packages... [RETURN]
dpkg-buildpackage: source package i3-wm
dpkg-buildpackage: source version 4.13-1gerardo+201705032120591
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Gerhard A. Dittes <maestro.gerardo@gmail.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build i3-gaps
dpkg-checkbuilddeps: error: Unmet build dependencies: libxcb-xrm-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

Based on the output, it might be possible to force the build, but I'm not knowledgable enough about dpkg to try it myself.

**Comment by hingino** [comment]
This seems to be a common problem with i3 gaps itself. This Reddit post claims to have a fix, but I haven't tried it: https://www.reddit.com/r/linuxquestions/comments/4owfz8/problem_installing_i3gaps_in_ubuntu_1604/?st=J29GY7GP&sh=4fedaa5f

**Comment by sitedyno** [comment]
There is a PPA which has this library: `ppa:aguignard/ppa`

**Comment by maestrogerardo** [comment]
@rynnon: Yes, that's true.  It's one of the reasons why _i3-gaps-deb_ (primarily) only supports "Ubuntu versions >= Yaketty" -- see [README.md](https://github.com/maestrogerardo/i3-gaps-deb/blob/master/README.md).

@hingino: Thanks for your comment.
@sitedyno: Thanks for mentioning the _ppa_.
