### ISSUE TITLE
Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by kafran** [maestrogerardo/i3-gaps-deb#11]
I think the `-y` of `apt-get/apt` should come after the `build-dep`.

```
sudo apt-get build-dep -y i3-wm
sudo apt build-dep -y i3-wm
sudo apt install -y
```
Also, how can I run this on a controlled environment avoiding to mess with my installed system installing all these dependencies? I'm not used to create deb packages. I was reading about pbuilder but I couldn't make this script work with it.

**Comment by maestrogerardo** [comment]
Hi,

I've just tested on a fresh 18.04 installation w/o any issues. (Perhaps another try with a new pull will do the trick for you.)

Regarding the controlled environment, e.g. _chroots_ are good way to go...

Cheers, Gerardo

**Comment by ghost** [comment]
I had the same issue with Linux Mint 19.2
I changed from `sudo apt -y build-dep i3-wm` to `sudo apt build-dep -y i3-wm` and it worked, otherwise apt just showed me the list of commands.

(I also changed `sudo apt -y install` to `sudo apt install -y`)
