### ISSUE TITLE
Please "debianise" https://github.com/Airblader/i3blocks-gaps too!

### ISSUE THREAD

**Issue by jaimet** [maestrogerardo/i3-gaps-deb#18]
Apologies for writing this here, but it seemed "kind of" the best place to request it. Could you please do the same thing with https://github.com/Airblader/i3blocks-gaps too? Thank you!

**Comment by barnumbirr** [comment]
I don't mean to intrude and usually don't advertise my own repositories on random issues but this hasn't gotten any traction so here it is:
i3blocks v1.5 is now compatible with i3-gaps but hasn't been updated in the Debian repositories for quite a while. I've created a repository to package and upload it until the repos are finally updated: https://github.com/barnumbirr/i3blocks-debian

Feel free to give it a spin.
Cheers.

**Comment by maestrogerardo** [comment]
Hi barnumbirr,

sorry for answering that late!

I was booked out (and exhausted) by several other projects (as well as private stuff), so that I did not found the time to have a deeper look into this.

Anyway, I'm glad that you've meanwhile found a way to help yourself along... 👍

Regards, Gerardo
