### ISSUE TITLE
make a non-git patch for 0001-debian-Disable-sanitizers.patch

### ISSUE THREAD

**Issue by laur89** [maestrogerardo/i3-gaps-deb#19]
Currently said patch only works in git repos; think it'd be better if the patch format was changed so it could also be applied to source tarballs instead of cloned git repos.

**Comment by maestrogerardo** [comment]
Hi laur89, sounds reasonable. But as this script itself uses (and therefore depends strongly on) git, anyway, I'll prefer to keep it that way (at least for convenience ;-) ).
