### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yanglei802** [maestrogerardo/i3-gaps-deb#24]
come on ,how can i to use it.the note is too simple.i i don't understand to how to install i3-gaps in debian10

**Comment by kaythomas0** [comment]
`git clone git@github.com:maestrogerardo/i3-gaps-deb.git`
`cd i3-gaps-deb`
`./i3-gaps-deb`

Then follow prompts on the terminal.

**Comment by maestrogerardo** [comment]
Thx @KevinNThomas for answering.
