### ISSUE TITLE
Script runs only after commenting out line #553

### ISSUE THREAD

**Issue by dogknowsnx** [maestrogerardo/i3-gaps-deb#28]
On my MX Linux 19.2 installation I got a "command not found" for
`	igd_checkHelp ${@}`
on initial execution.

No biggy. I tried to find a hint at why this message appears, but to no avail. Commenting out the line above fixed it for me.

Thanx for this fantastic tool!

**Comment by maestrogerardo** [comment]
Hi manfred3000,

I cannot reproduce (nor understand) your described behavior. Therefore I'm closing this issue. Please reopen if I'm still wrong (with some additional console output and the like)...

Cheers!

**Comment by dogknowsnx** [comment]
Thanks for the reply.
I'm not on Debian anymore so can't test/reproduce any further.
