### ISSUE TITLE
The .deb file generated with this script needs libasan3 as a dependency

### ISSUE THREAD

**Issue by ghost** [maestrogerardo/i3-gaps-deb#6]
I am curious why is `libasan3` needed as dependency for i3-gaps?

I read on i3-gaps [Ubuntu dependencies page](https://github.com/Airblader/i3/wiki/Compiling-&-Installing#ubuntu--1404-lts--1604), and `libasan3` is not listed.

I just want to install i3-gaps on Ubuntu 16.04.

The previous last .deb file I generated is `i3-wm_4.14-1gerardo+201709071758481_amd64.deb` and this is installable on Ubuntu 16.04

**Comment by maestrogerardo** [comment]
Hi alekcacko,

sorry, this question should rather go the author of i3 (/i3-gaps). This tool (i3-gaps-deb) does not change the dependency settings from the original project (at least not in _that way_).

I tested several Ubuntu versions (some time ago) and for me only _Ubuntu "yakkety"_ and later versions have worked out -- as you can read here: https://github.com/maestrogerardo/i3-gaps-deb/blob/master/README.md (section: _Works for what?_).

(I personally use raw Debian.)

Regards, Gehard
