### ISSUE TITLE
Why this script doesn't work on Ubuntu 16.04?

### ISSUE THREAD

**Issue by ghost** [maestrogerardo/i3-gaps-deb#8]

**Comment by maestrogerardo** [comment]
Hi,

because the build dependencies can't be met (easily). See also [this](https://github.com/maestrogerardo/i3-gaps-deb/issues/1) issue.

Regards...

**Comment by ysolis** [comment]
you can suggest in the installer if the distro detected is xenial to add the PPA, or add the PPA how part of the process
